repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json

#  - repo: https://github.com/astral-sh/ruff-pre-commit
#  # Ruff version.
#    rev: v0.1.6
#    hooks:
#      - id: ruff
#        exclude: |
#            (?x)^(
#                tests/.*|
#                scripts/.*
#            )$
#      - id: ruff-format
#        exclude: |
#          (?x)^(
#              tests/.*|
#              scripts/.*
#          )$
