#!/usr/bin/env python
"""
Copyright (C) 2016 Jakub Krajniak <jkrajniak@gmail.com>

This file is distributed under free software licence:
you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import argparse
import datetime
import numpy as np
import math


def _args():
    parser = argparse.ArgumentParser(
        description='Converts LAMMPS tabulated potentials to GROMACS format')
    parser.add_argument('input_file')
    parser.add_argument('output_file')
    parser.add_argument('--table_type', choices=('pair',),
                        default='pair')
    parser.add_argument('--length_scale', default=1.0, type=float)

    return parser.parse_args()


def _pair_convert(input_f, output_f, args):
    in_f = np.loadtxt(input_f)
    outf = np.zeros((in_f.shape[0], 7))
    outf[:, 0] = in_f[:, 0]
    outf[:, 5] = in_f[:, 1]
    np.savetxt(output_f, outf, header='Converted ESPP to GROMACS, {} to {}, {}'.format(
        input_f, output_f, datetime.datetime.now()))

def main():
    args = _args()
    input_f = open(args.input_file, 'r')
    output_f = open(args.output_file, 'w')

    table_type2func = {
        'pair': _pair_convert,
    }

    table_type2func[args.table_type](input_f, output_f, args)

    output_f.close()
    input_f.close()

if __name__ == '__main__':
    main()
