#!/bin/bash
#
# Copyright (C) 2015 Jakub Krajniak <jkrajniak@gmail.com>
#
# Distributed under terms of the GNU GPLv3 license.
#
# It moves you to the workdir of specific job.
#

DIR=`qstat -f $1 | grep -A 1 WORKDIR | tr '\n' ' ' | sed -e 's/\t//g; s/ //g' | cut -f1 -d',' | cut -f2 -d'='`
cd $DIR
