#!/bin/bash
#
# Copyright (C) 2015 Jakub Krajniak <jkrajniak@gmail.com>
#
# Distributed under terms of the GNU GPLv3 license.
#
# It will login via ssh to the computing node of the job.
#

HOST="`qstat -f $1 | grep exec_host | cut -f2 -d= | cut -f1 -d+ | cut -f1 -d/`"
ssh -X $HOST
